# ==========================
# Pinhole front projection
# ==========================
camera360_pinhole_front:
  ros__parameters:
    update_rate: 10.0
    always_recompute_mapping: false
    base_frame: camera360_center_link
    pose: [0.0, 0.0, 0.0, 0.0, 0.4, 0.0]
    virtual_sensor_frame: pinhole_front_camera_frame
    virtual_sensor_optical_frame: pinhole_front_optical_frame
    projection_type: image_projection_plugins::PinholeProjection
    projection_parameters:
      image_width: 1024
      image_height: 512
      horizontal_fov: 130.0
      focal_length: 1.0

# ==========================
# Mercator projection
# ==========================
camera360_mercator_projection:
  ros__parameters:
    update_rate: 10.0
    base_frame: camera360_center_link
    pose: [0.0, 0.0, 0.0, 0.0, 0.0, 3.141592]
    projection_type: image_projection_plugins::MercatorProjection
    projection_parameters:
      image_width: 1024
      image_height: 400
      cylinder_radius: 1.0

# ==========================
# Left fisheye
# ==========================
camera360_left_fisheye:
  ros__parameters:
    update_rate: 10.0
    always_recompute_mapping: false
    base_frame: camera360_center_link
    pose: [0.0, 0.0, 0.0, 0.0, 0.0, 1.57]
    virtual_sensor_frame: camera360_ideal_fisheye_left_link
    virtual_sensor_optical_frame: camera360_ideal_fisheye_left_optical_frame
    projection_type: image_projection_plugins::IdealFisheyeProjection
    projection_parameters:
      image_width: 512
      image_height: 512
      fov: 180.0
      sphere_radius: 1.0

# ==========================
# Right fisheye
# ==========================
camera360_right_fisheye:
  ros__parameters:
    update_rate: 10.0
    always_recompute_mapping: false
    base_frame: camera360_center_link
    pose: [0.0, 0.0, 0.0, 0.0, 0.0, -1.57]
    virtual_sensor_frame: camera360_ideal_fisheye_right_link
    virtual_sensor_optical_frame: camera360_ideal_fisheye_right_optical_frame
    projection_type: image_projection_plugins::IdealFisheyeProjection
    projection_parameters:
      image_width: 512
      image_height: 512
      fov: 180.0
      sphere_radius: 1.0

