enable_depth: true

depth_module:
  enable_auto_exposure: true   # Set false if you want manual exposure below
  # exposure: 8500              # Commented out because auto exposure is enabled
  gain: 16

decimation_filter:
  enable: true
  filter_magnitude: 2

spatial_filter:
  enable: true
  filter_magnitude: 2
  filter_smooth_alpha: 0.5
  filter_smooth_delta: 20
  holes_fill: 3

temporal_filter:
  enable: true
  filter_smooth_alpha: 0.4
  filter_smooth_delta: 20

hole_filling_filter:
  enable: true
  fill_type: 1  # Nearest neighbor (recommended)

align_depth:
  enable: false

clip_distance: 5.0

publish_tf: true
tf_publish_rate: 30.0

pointcloud:
  enable: false

rgb_camera:
  power_line_frequency: 2  # 0=disabled, 1=50Hz, 2=60Hz (choose accordingly)

al_filter:
  enable: true  # Reduces temporal noise
