ublox_gps_node:
  ros__parameters:
    device: "/dev/ttyACM0"
    frame_id: "gps_link"
    rate: 4.0
    debug: 0
    nav_rate: 1.0
    enable_pps: false
    dgnss_mode: 3
    dynamic_model: airborne1
